### ISSUE TITLE
NetCDF handler not registered

### ISSUE THREAD

**Issue by jblarsen** [pydap/pydap#129]
When I do a fresh install of pydap (python3 setup.py install --user) the built-in NetCDF handler does not seem to be enabled. I believe an entry point for it in setup.py is needed:

```
$ git diff setup.py
diff --git a/setup.py b/setup.py
index 7471f20..ba25bd1 100644
--- a/setup.py
+++ b/setup.py
@@ -97,6 +97,9 @@ setup(name='Pydap',
       },
       test_suite="pydap.tests",
       entry_points="""
+            [pydap.handler]
+            nc = pydap.handlers.netcdf:NetCDFHandler
+
             [pydap.response]
             das = pydap.responses.das:DASResponse
             dds = pydap.responses.dds:DDSResponse
```

At least it works in my case after doing that. The same procedure probably applies for the CSV handler.

Best regards,
Jesper

**Comment by Alexander-Barth** [comment]
I have exactly the same issue with a clean install in a Docker environment.

**Comment by Alexander-Barth** [comment]
I can confirm that the fork at https://github.com/jblarsen/pydap works. Hopefully, this change will get integrated.
