### ISSUE TITLE
add support for CSW capability via pycsw

### ISSUE THREAD

**Issue by tomkralidis** [pydap/pydap#137]
cc @robertodealmeida, @kwilcox, @rsignell-usgs

Following on from https://github.com/geopython/pycsw/issues/157
The pydap OPeNDAP implementation (http://pydap.org && https://github.com/robertodealmeida/pydap) provides the ability to write extensions to serve out things like WMS, KML, etc.

Investigate the ability to integrate pycsw as a library as a pydap response module, thus exposing pydap contents via CSW for search/discovery.

Thoughts/ideas:

- a `pydap.responses.csw` plugin would:
  - provide a single URL (`/csw`?) which would allow CSW search atop the entire directory tree
  - provide a backend/offline utility to walk the directory tree looking for, say, `*.xml` files representing metadata.  Or, configuration of the plugin could allow setting a metadata directory that would be walked instead
 - metadata formats supported would be those supported by pycsw (ISO, DC, FGDC, DIF, etc.)

**Comment by rsignell-usgs** [comment]
Our current workflow is to harvest ISO records from THREDDS catalogs using filters to create only the records we want.  This allows us to do things like select only  aggregated datasets, skipping the granule netcdf files, or get select or ignore specific directories.   We usually collect ISO records from multiple servers and then feed those into our pycsw.    I'm not sure a CSW service for pydap would be that useful.  What is the use case?

**Comment by tomkralidis** [comment]
The use case would be to install pycsw as part of a pydap deployment/installation.  So a single pydap deployment with a pycsw plugin in the same instance/container. Esoteric perhaps :)

**Comment by tomkralidis** [comment]
Closing, we should be able to install pydap and pycsw seprately and have pycsw point to pydap entries all the same.
