### ISSUE TITLE
requests missing from requirements

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [pydap/pydap#145]
It appears pydap uses the requests pacakge, but it's not listed in the setup.py:

```
install_requires = [
    'numpy',
    'Webob',
    'Jinja2',
    'docopt',
    'six >= 1.4.0',
    'beautifulsoup4'
]
```

**Comment by jameshiebert** [comment]
It's not *missing* per se, it's actually listed in the cas (Client Authentication Services) extras.

```bash
hiebert@pcic-2004:~/code/pydap$ grep -a1 requests setup.py
cas_extras = [
    'requests',
    'lxml'
--
    'pytest-attrib',
    'requests-mock',
    'requests'
]
```

To get it installed, you just have to add the extra parameter to your install line:

```bash
pip install -e .[cas]
```

**Comment by tomkralidis** [comment]
Perhaps `cas_extras` should be renamed to `client_extras`, or `client_extras` is introduced which provided just `requests` and `cas_extras` provides `lxml`.  It's clear that the `src/pydap/client.py` breaks without `requests`. 

Thoughts? Docs can be updated thereafter.

**Comment by jameshiebert** [comment]
> It's clear that the ``src/pydap/client.py`` breaks without ``requests``.

Yes, that's a good point. I'd be amenable to that. @laliberte the CAS and client stuff is mostly your work. Do you have any opinions on the matter?

**Comment by laliberte** [comment]
I can confirm that ``requests`` should be required for the client. This was overlooked when #99 was merged. The ``requests`` package is required to ensure that redirects are followed through. Should we simply require it for ``pydap`` at large?

**Comment by tomkralidis** [comment]
IMHO better not to. From a server perspective requests is not required right? As a server deployment it would mean less moving parts. Thoughts?

**Comment by wholmgren** [comment]
I raised the same issue in #120. My vote is for including requests in install_requires.

**Comment by ChrisBarker-NOAA** [comment]
On Thu, Sep 21, 2017 at 2:59 PM, Tom Kralidis <notifications@github.com>
wrote:

> IMHO better not to. From a server perspective requests is not required
> right? As a server deployment it would mean less moving parts.


requests is pretty lightweight and easy to install, so not a heavy lift.

at the end of the day, pip doesn't handle optional dependencies well, so
most folks err on the side of including stuff.

what yu really want is for folks to be able to :

pip install pydap

and then have everything work.

if you realy want to keep it minimal, you would need to:

break out packages:

pydap-server
pydap-client

or something like that.

or, _maybe_ add some wrapper code in pydap:

try:
    import requests
except ImportError:
    print("pydap requires the requests module for this functionality -- you
can get it with:\n pip install requests")
    raise

I've done that for, say optional matplotlib use -- but I wouldn't bother
for requests -- it's pretty lightweight.

-CHB


-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by tomkralidis** [comment]
@laliberte @wholmgren @ChrisBarker-NOAA thanks for the info.  I like the idea of splitting between `pydap-client` and `pydap-server` but that's a longer term move that needs more discussion.

Having said this, sounds like the path forward is to include `requests` as part of Pydap proper.  I'll issue a PR shortly.
