### ISSUE TITLE
Documentação da versão 3.1.1.

### ISSUE THREAD

**Issue by jonascavalcantineto** [pydap/pydap#154]
No site a documentação esta indisponivel da versão 3.1.1, como posso conseguir?

**Comment by jameshiebert** [comment]
Yeah, as far as I can tell, Read the Docs will only build the documentation using Python 3. Prior to Pydap 3.2, Pydap did not support Python 3, so the doc build fails. The thing is, all of the documentation history (including 3.1.1) is still in the git repo, and it's written in RST, so it renders on GitHub. It's non-ideal, but you can read it file-by-file [here](https://github.com/pydap/pydap/tree/3.1.1/docs). Better than nothing.
