### ISSUE TITLE
Host Pydap's documentation on Read the Docs

### ISSUE THREAD

**Issue by jameshiebert** [pydap/pydap#16]
As discussed in #14, we need to transition Pydap's documentation hosting to something that can be maintained by the community. [Read the Docs](https://readthedocs.org/) was favored by most, and I support that as well, but there have been some challenges [building the documentation](https://readthedocs.org/projects/pydap/builds/3977804/).

@shoyer To fix the import error, I think that you just have to [enable virtualenv](http://read-the-docs.readthedocs.io/en/latest/faq.html#my-project-isn-t-building-with-autodoc) in the "Advanced settings" tab. Alternatively (or in addition to), you can add me as a collaborator, and I can work on fixing it.

**Comment by shoyer** [comment]
Just added you as a maintainer for RTD

**Comment by jameshiebert** [comment]
Thanks

**Comment by lewismc** [comment]
BTW, it looks like the builds are working just fine on RTFD however it also looks like the project has not been published... or something else
https://readthedocs.org/projects/pydap/builds/4580394/

**Comment by jameshiebert** [comment]
"Latest" in RTD points to master, so that will all get resolved when I merge `develop` with `master`. But if you try to read the version "develop": http://pydap.readthedocs.io/en/develop/ everything's all good.

**Comment by robertodealmeida** [comment]
I still have pydap.org, should I point it to http://pydap.readthedocs.io/en/latest/?

**Comment by shoyer** [comment]
> I still have pydap.org, should I point it to http://pydap.readthedocs.io/en/latest/?

Makes sense to me. See http://read-the-docs.readthedocs.io/en/latest/alternate_domains.html#cname-support

**Comment by jameshiebert** [comment]
That'd be great @robertodealmeida. Thanks! With that and the newly built latest on RTFD, I think we should be good to go here, so I'm closing this issue. Thanks for the collaborative effort!

**Comment by robertodealmeida** [comment]
Cool, www.pydap.org now points to readthedocs.io, and pydap.org redirects to www.pydap.org. Some still needs to do the second step, "Add a Domain object in the Project Admin > Domains page for your project."

**Comment by shoyer** [comment]
Seems to be working now at www.pydap.org
