### ISSUE TITLE
Anaconda installs pydap 3.2.1

### ISSUE THREAD

**Issue by rocheseb** [pydap/pydap#160]
With a fresh install of Anaconda on linux, I installed pydap with 

`conda install pydap`

which installed version 3.2.1 instead of 3.2.2, and the latest version is not found with 

`conda install pydap=3.2.2`

I had to uninstall it and reinstall it with

`pip install pydap`

which installs the latest 3.2.2

**Comment by jameshiebert** [comment]
Sorry, we don't maintain conda or the [conda package repository](https://anaconda.org/anaconda/repo), so I'm not really sure what this has to do with us. What is it that you're asking for here?
