### ISSUE TITLE
open_url(): UnicodeDecodeError

### ISSUE THREAD

**Issue by flackdl** [pydap/pydap#162]
`open_url()` is throwing a `UnicodeDecodeError` error for http://oos.soest.hawaii.edu/erddap/griddap/NCEP_Global_Best.nc.  

I know if you request the entire file (i.e via curl) the server will throw a *HTTP Status 500 - Your query produced too much data*, but I believe this module does lazy loading so I don't understand what could be happening, unless it is indeed an encoding issue.

Anyone know what I may be stumbling with? 

```python
>>> from pydap.client import open_url
>>> dataset = open_url('http://oos.soest.hawaii.edu/erddap/griddap/NCEP_Global_Best.nc')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    dataset = open_url('http://oos.soest.hawaii.edu/erddap/griddap/NCEP_Global_Best.nc')
  File "/home/danny/.virtualenvs/cwwed-env/lib/python3.6/site-packages/pydap/client.py", line 67, in open_url
    timeout).dataset
  File "/home/danny/.virtualenvs/cwwed-env/lib/python3.6/site-packages/pydap/handlers/dap.py", line 54, in __init__
    raise_for_status(r)
  File "/home/danny/.virtualenvs/cwwed-env/lib/python3.6/site-packages/pydap/net.py", line 34, in raise_for_status
    detail=response.status+'\n'+response.text,
  File "/home/danny/.virtualenvs/cwwed-env/lib/python3.6/site-packages/webob/response.py", line 635, in _text__get
    return body.decode(decoding, self.unicode_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
>>> 
```

**Comment by flackdl** [comment]
I should note this arises with python `2.7` and `3.6`.

**Comment by flackdl** [comment]
It looks like https://github.com/pydap/pydap/pull/152 solves the problem, which is gzip compression handing.  I found the reference on the [mailing list](https://groups.google.com/forum/#!topic/pydap/el4r1s0O6PI).  I'll close this since it's a duplicate.

**Comment by jameshiebert** [comment]
And it should be handled by #127, which has already been merged into master. So the next release should take care of this issue for you.

And FYI, if the server throws a 500 error that's a *server* error. So it doesn't matter that the pydap *client* can stream data from the server. If the server can't stream data *to* the client (and to my knowledge ERDDAP cannot), there's nothing you can do from the client side except make multiple smaller requests and append them together.

**Comment by tahaum** [comment]
I'm experiencing the same problem. Original error:

`ds = open_url('https://thredds.met.no/thredds/dodsC/meps25epsarchive/2017/10/29/meps_mbr0_pp_2_5km_20171029T00Z.nc')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-63f3aa299554> in <module>()
----> 1 ds = open_url('https://thredds.met.no/thredds/dodsC/meps25epsarchive/2017/10/29/meps_mbr0_pp_2_5km_20171029T00Z.nc')

c:\users\bruker\appdata\local\programs\python\python36\lib\site-packages\pydap\client.py in open_url(url, application, session, output_grid, timeout)
     65     """
     66     dataset = DAPHandler(url, application, session, output_grid,
---> 67                          timeout).dataset
     68 
     69     # attach server-side functions

c:\users\bruker\appdata\local\programs\python\python36\lib\site-packages\pydap\handlers\dap.py in __init__(self, url, application, session, output_grid, timeout)
     55         if not r.charset:
     56             r.charset = 'ascii'
---> 57         dds = r.text
     58 
     59         dasurl = urlunsplit((scheme, netloc, path + '.das', query, fragment))

c:\users\bruker\appdata\local\programs\python\python36\lib\site-packages\webob\response.py in _text__get(self)
    620         decoding = self.charset or self.default_body_encoding
    621         body = self.body
--> 622         return body.decode(decoding, self.unicode_errors)
    623 
    624     def _text__set(self, value):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
`

I tried #152 but now I get this error:

`ds = open_url('https://thredds.met.no/thredds/dodsC/meps25epsarchive/2017/10/29/meps_mbr0_pp_2_5km_20171029T00Z.nc')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-63f3aa299554> in <module>()
----> 1 ds = open_url('https://thredds.met.no/thredds/dodsC/meps25epsarchive/2017/10/29/meps_mbr0_pp_2_5km_20171029T00Z.nc')

c:\users\bruker\appdata\local\programs\python\python36\lib\site-packages\pydap\client.py in open_url(url, application, session, output_grid, timeout)
     65     """
     66     dataset = DAPHandler(url, application, session, output_grid,
---> 67                          timeout).dataset
     68 
     69     # attach server-side functions

c:\users\bruker\appdata\local\programs\python\python36\lib\site-packages\pydap\handlers\dap.py in __init__(self, url, application, session, output_grid, timeout)
     52         ddsurl = urlunsplit((scheme, netloc, path + '.dds', query, fragment))
     53         r = GET(ddsurl, application, session, timeout=timeout)
---> 54         raise_for_status(r)
     55         if not r.charset:
     56             r.charset = 'ascii'

c:\users\bruker\appdata\local\programs\python\python36\lib\site-packages\pydap\net.py in raise_for_status(response)
     31 def raise_for_status(response):
     32     # Raise error if status is above 300:
---> 33     if response.status_code >= 300:
     34         raise HTTPError(
     35             detail=response.status+'\n'+response.text,

AttributeError: 'NoneType' object has no attribute 'status_code'`
