### ISSUE TITLE
pydap.org not responding

### ISSUE THREAD

**Issue by tomkralidis** [pydap/pydap#169]
Looks like hitting http://pydap.org results in a timeout.

I'm not sure where/how pydap.org is setup.  @betodealmeida are you aware of any configurations?  I'd propose a GitHub pages setup so long as pydap.org DNS is setup accordingly.

**Comment by betodealmeida** [comment]
Hi, Tom! Looks like the domain expired earlier this month. I just renewed it for another year, and it's working again. It points to the read-the-docs website that someone set up some time ago.

Thanks for leading the effort on reviving Pydap, by the way. I'm planning on attending the meeting, and I'm curious about the state of its web UI — It would be nice to modernize it with React, and maybe integrate with data visualization tools, and I could maybe contribute to that.

**Comment by tomkralidis** [comment]
Thanks @betodealmeida!  Awesome news that you'll be at our meeting on Friday!

**Comment by tomkralidis** [comment]
@betodealmeida when I try https://pydap.org I get a timeout (http://pydap.org works fine).  Is this something you can enable on your end?

**Comment by betodealmeida** [comment]
I think so... https://www.pydap.org/ works for me, but not https://pydap.org. I'll take a look at the DNS config.

**Comment by betodealmeida** [comment]
I pointed pydap.org to 104.18.231.122 (the IP for readthedocs.io), since the root record cannot use a `CNAME`. Now it resolves, but returns a 403. Maybe something needs to be changed in readthedocs?

**Comment by betodealmeida** [comment]
https://github.com/rtfd/readthedocs.org/issues/2652

**Comment by tomkralidis** [comment]
Any idea who has readthedocs credentials? https://readthedocs.org/projects/pydap/ ?

**Comment by betodealmeida** [comment]
@shoyer and @jameshiebert

**Comment by tomkralidis** [comment]
If someone can take a look or add me (rtd username=tomkralidis) to Pydap I can take a look.

**Comment by tomkralidis** [comment]
thanks @shoyer.  I've added HTTPS support in RTD.  When https://pydap.org I get:

> pydap.org uses an invalid security certificate. The certificate is only valid for the following names: ssl905239.cloudflaressl.com, *.readthedocs.io, readthedocs.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl

@betodealmeida does the DNS  need to point to readthedocs.io instead?

**Comment by tomkralidis** [comment]
Looks like https://www.pydap.org works but http://pydap.org does not.

The lack of a root A record to readthedocs may be the issue.  Perhaps once #170 is implemented this will be a moot point given GitHub pages supports apex domains.

**Comment by laliberte** [comment]
Both links are working for me. @tomkralidis can you confirm? We could probably close this thread.

**Comment by epifanio** [comment]
it looks like is down now -

**Comment by tomkralidis** [comment]
cc @betodealmeida 

looks like https://www.pydap.org works but http://pydap.org/ does not. I'm guessing it's a DNS / CNAME issue.

**Comment by tomkralidis** [comment]
@betodealmeida any chance you can look into the DNS issues?  Website continues to be down.

**Comment by betodealmeida** [comment]
Sure, let me take a look.On Sep 20, 2019 11:07 AM, Tom Kralidis <notifications@github.com> wrote:@betodealmeida any chance you can look into the DNS issues?  Website continues to be down.

**Comment by betodealmeida** [comment]
Fixed sorry. For the naked domain I need to point to the IP, and looks like it changed. Not sure how to fix this permanently.
