### ISSUE TITLE
build out proper website

### ISSUE THREAD

**Issue by tomkralidis** [pydap/pydap#170]
cc @betodealmeida 

Currently, hitting http://pydap.org redirects to the readthedocs setup.  This is for Pydap documentation proper tied to a given version.

It would be valuable to build out a proper, simple website presence via GitHub pages.  The website would contain version independent information (community, features, downloads, etc.) and live in `gh-pages`, for example, or a dedicated pydap.org repository.

**Comment by 7yl4r** [comment]
I see you created a separate repo over at https://github.com/pydap/pydap.org . Jekyll/gh-pages in a separate repo is the way to go, so :+1: for that. I will follow over there and watch for any technical issues I might be able to help with.

**Comment by captainkirk99** [comment]
Currently we are using the gh-pages website to serve the latest version of the docs. On other projects, I have extended this to show multiple versions of the documentation, but I am not intending to do that here.

In olden times packages had their own sites and did everything there. But nowadays, plenty of projects just use GitHub as their main site. I suggest that pydap do the same. Downloads and releases are already well-handled. The current documentation can be in gh-pages, and the README can contain any general information about community, features, etc.

I am going to close this issue. If anyone is interested in further development of the gh-pages branch, please re-open this issue, and describe specifically what is proposed.
