### ISSUE TITLE
Drop python 3.4

### ISSUE THREAD

**Issue by laliberte** [pydap/pydap#175]
Should python 3.4 support be dropped?

**Comment by tomkralidis** [comment]
@laliberte what's the rationale for dropping 3.4?  What 3.x versions should we officially support?

**Comment by laliberte** [comment]
The main reason is that python 3.4 will have its final release in Q1 2019 and that travis builds with 3.4 are longer than with other python versions (IMHO this should be a sufficient reason). As for supported versions, we should probably add python 3.7 when we remove 3.4. This way we keep support for 4 python versions.

**Comment by tomkralidis** [comment]
Thanks @laliberte will do.

Total aside: @laliberte can you contact me tomkralidis@gmail.com offline concerning pydap?

**Comment by tomkralidis** [comment]
PR in #176, looks like a few issues to fix to cover 3.7

**Comment by hugovk** [comment]
By the way, here's the pip installs for pydap from PyPI for last month, showing very low numbers for 3.4:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  61.79% |     1,365 |
|      2.7 |  23.31% |       515 |
| null     |  10.00% |       221 |
|      3.7 |   1.95% |        43 |
|      3.4 |   1.81% |        40 |
|      3.5 |   1.13% |        25 |
| Total    |         |     2,209 |


Source: `pypistats python_minor --last-month pydap`

**Comment by Juanlu001** [comment]
Done in #192.
