### ISSUE TITLE
Incomplete list of install dependencies

### ISSUE THREAD

**Issue by ghisvail** [pydap/pydap#18]
`pydap/wsgi/cache.py` requires `h5py`, `requests` and `webob`, which are not listed as install requirements. I am surprised travis has not picked that up, assuming it is operational for `pydap`.

**Comment by ghisvail** [comment]
Or they could be in `extras_require` assuming `pydap.wsgi` is considered optional.

**Comment by jameshiebert** [comment]
This had been fixed in the [develop](/pydap/pydap/tree/develop) branch (13e215d1, 245a979e), but unfortunately has yet to make it to [master](/pydap/pydap/tree/master). I think that *should* happen in the next month or so, so please stay tuned.

**Comment by ghisvail** [comment]
@jameshiebert please ping me here when the release is made. Cheers.

**Comment by ghisvail** [comment]
Any progress?

**Comment by lewismc** [comment]
@jameshiebert this issue can be closed off.
