### ISSUE TITLE
Merge URS authentication branch

### ISSUE THREAD

**Issue by jgallagher59701** [pydap/pydap#20]
The Merge request for the URS authentication seems like it's languishing. See Pull request #11 (Added support for NASA/URS SSO service)

Thanks,
James

**Comment by bucricket** [comment]
Thanks to James for adding this.  This is really needed now that NASA requires logins through https://urs.earthdata.nasa.gov.  Please merge this!

Thanks!
Mitch

**Comment by pmacaodh** [comment]
I second that and would rather use the production version than the branch to access the data.  Thanks.

**Comment by jameshiebert** [comment]
Addressed by #28
