### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by nathanlcarlson** [pydap/pydap#202]
As reported in the pydap.org repository https://github.com/pydap/pydap.org/issues/1 it appears the pydap.org site is unavailable.

**Comment by neishm** [comment]
Looks like this issue is already reported in #169.  The alternate URL https://www.pydap.org still works.

**Comment by nathanlcarlson** [comment]
Okay, should probably put that one in the header line at the top of this repository.

**Comment by tomkralidis** [comment]
Closing as duplicate of #169.  The pydap/pydap.org repository is since deleted given we kept the website setup in pydap/pydap proper.
