### ISSUE TITLE
module 'pydap' has no attribute '__version__'

### ISSUE THREAD

**Issue by rabernat** [pydap/pydap#206]
I just installed the latest version of pydap from pip.

```python
import pydap
print(pydap.__version__)
```

```
AttributeError: module 'pydap' has no attribute '__version__'
```

This feels like very strange behavior for a python package...

**Comment by tomkralidis** [comment]
(sorry, it's been awhile!)

@rabernat FYI this was implemented in https://github.com/pydap/pydap/pull/135, but we need to make a release.  Will close this one and suggest following #212.
