### ISSUE TITLE
ImportError: cannot import name 'PasterServerApplication' from 'gunicorn.app.pasterapp' 

### ISSUE THREAD

**Issue by albertotb** [pydap/pydap#207]
Since the last Pypi version (3.2.2) I'm getting this error: 

    Traceback (most recent call last):
      File "/home/alberto/anaconda3/bin/pydap", line 10, in <module>
        sys.exit(main())
      File "/home/alberto/anaconda3/lib/python3.7/site-packages/pydap/wsgi/app.py", line 225, in main
        from gunicorn.app.pasterapp import PasterServerApplication
    ImportError: cannot import name 'PasterServerApplication' from 'gunicorn.app.pasterapp' 
    (/home/alberto/anaconda3/lib/python3.7/site-packages/gunicorn/app/pasterapp.py)

I'm running Python 3.7. It seems that the gunicorn 20.0 update broke pydap. Downgrading to gunicorn 19.9 fixes the issue

**Comment by tshead2** [comment]
Confirmed.

**Comment by jondoesntgit** [comment]
Is there any devs who are still maintaining this project and are going to address this?

**Comment by raphaeljolivet** [comment]
Hi, I just made a PR to fix this bug : https://github.com/pydap/pydap/pull/286

Hi feel PyDap is really a great project and does not get the attention it deserve.
I plan to make some more contributions of features that are required in [our projects](https://github.com/oie-mines-paristech) :
- Basic Auth
- Pulling metadata (time & space extends, keywords etc) from NetCDF following CF conventions to Thredds XML catalog
- Up to date Docker / docker-compose packaging
