### ISSUE TITLE
providing up-to-date Pypi package

### ISSUE THREAD

**Issue by jerabaul29** [pydap/pydap#212]
It looks like the last PyDap release was in 2017 from the information on this page:

https://pypi.org/project/Pydap/#history

The package installed through pip is therefore quite outdated. For example, using pydap obtained from a pip install, this issue:

https://github.com/pydap/pydap/issues/162

is present, while using pydap installed from a git clone and local install, the issue is solved...

Therefore, would it be possible for the maintainer / owner of pydap here / on Pypi to push the up-to-date code to Pypi? :)

**Comment by amotl** [comment]
Hi there,

first of all, I would like to salute @betodealmeida, @laliberte, @jameshiebert, @tomkralidis and all other contributors for conceiving and maintaining this excellent software package.

After coming here through https://github.com/earthobservations/wetterdienst/discussions/287#discussioncomment-223753 as suggested by @mhaberler, we found the package to be a little bit unmaintained. However, thanks to different fixes and suggestions by community members (thanks @jerabaul29, @jblarsen, @MBARIMike and @mhaberler) on behalf of #167, #197 and #217, we have been able to successfully, install, run and operate both a Pydap server and the respective client.

In this manner, we wanted to take the chance to contribute the canonical installation command which will make things work. We hope it will be useful for others until an updated package will be available from PyPI.
```
pip install git+https://github.com/jblarsen/pydap.git#egg=pydap[server,handlers.netcdf] gunicorn==19.10.0
```

With kind regards,
Andreas.

**Comment by observingClouds** [comment]
Hi there,

I want to support the request of a new pypi package. We currently develop a tool for a broader community, where we rely on the solution of #154 which has been merged in October 2018. The dependency to this package could be mentioned in the `requirements.txt` by e.g.
```
-e git+https://github.com/pydap/pydap#egg=pydap
```
but we would much rather prefer to be more general and reference it by e.g. `pydap>=3.2.3`.

This is a great package and more and more scientific data is available through OPeNDAP and users accessing it might rely on this package. Are you planning to make a new release? I'm happy to help where I can.

All the best,
Hauke

**Comment by pmav99** [comment]
Even if a release to PyPi is not feasible at the moment could we at least have a new `git tag` created? At the very least, this wou8ld allow to update the `conda-forge` package 

https://github.com/conda-forge/pydap-feedstock/blob/d44ff3fec96792ea837d30fb5defa44a205a71a4/recipe/meta.yaml#L1-L11

pinging @tomkralidis since he is the one that merged the latest Pull Requests

**Comment by tomkralidis** [comment]
Thanks for the report @pmav99 et al.  We will be cutting a new release shortly.

cc @jgallagher59701

**Comment by captainkirk99** [comment]
A new release has been dropped.

I need to submit it to PyPi next...

**Comment by pmav99** [comment]
Any updates on the PyPi package?

For the record, we want to release a package that depends on pydap 3.3.0 and we can't do so because when we try to upload our package, PyPi rejects it with:

> `  HTTP Error 400: Invalid value for requires_dist. Error: Can't have direct dependency: 'pydap @ https://github.com/pydap/pydap/archive/refs/tags/3.3.0.zip'`

This is a known issue that has been resolved as "won't fix". Further info: https://github.com/pypa/warehouse/issues/9404

**Comment by tomkralidis** [comment]
@captainkirk99 any update on PyPI publishing?

**Comment by pmav99** [comment]
Just a reminder, if you find the time to pubilsh on PyPI, it would be really great :)

**Comment by zachsa** [comment]
the most resent version on PyPI is from 2017 - are there any reasons not to publish 3.3.0 to PyPI?

**Comment by tomkralidis** [comment]
@captainkirk99 any update on PyPI publishing?

**Comment by pmav99** [comment]
Don't want to be a pest, but a PyPI release would be great! :)

Since @captainkirk99 is not responding (I really hope everything is fine..) I am pinging the other maintainers of the pydap package on PyPI hoping that they still have access: @shoyer @betodealmeida @jameshiebert

**Comment by kandersolar** [comment]
Now that v3.4.0 and v3.4.1 are on [PyPI](https://pypi.org/project/pydap/#history), I think this issue can be closed :)

**Comment by Mikejmnez** [comment]
Closing this issue as this has been addressed by a new PyPI release last year 🚀
