### ISSUE TITLE
accessing pydap.org results in DNS error

### ISSUE THREAD

**Issue by tomkralidis** [pydap/pydap#233]
Accessing http://pydap.org results in a DNS error on Cloudflare:

```
Error 1001 Ray ID: 6d0baf337a522286 • 2022-01-20 22:19:26 UTC
DNS resolution error
```

For background, we last looked at this during #169, and it appears that pydap.org is supposed to point to readthedocs.

@betodealmeida any idea on the DNS side?

cc @betodealmeida @jgallagher59701

**Comment by betodealmeida** [comment]
The domain hasn't expired, and I haven't changed anything. I'm not super familiar with using a custom domain with readthedocs, but I can point it somewhere else if the IP has changed.

**Comment by tomkralidis** [comment]
@betodealmeida current RTD setup says:

> To configure this domain add a CNAME record in your DNS pointing your custom domain to readthedocs.io. 

While we are at it, it's probably a good time to fix the HTTPS support.

**Comment by captainkirk99** [comment]
OK, I have set up pydap docs on the GitHub gh-pages branch, which is a newish feature of GitHub that allows repos to put their documentation up on the web.

If you want to spin up a pydap.org site and put the docs there, go for it. But I don't think it's needed.

**Comment by captainkirk99** [comment]
I note there is also a broken link to pydap.org on the main GitHub page (upper right). So we should either fix the server or remove the link.
