### ISSUE TITLE
Release version 3.3.0?

### ISSUE THREAD

**Issue by captainkirk99** [pydap/pydap#240]
I believe there is general consensus that a release should be done before any further major changes. Does that make sense to everyone?

I propose a release after the following issues are resolved: 
* #237 
* #231 
* #203 
* #227 

Basically the idea is to get tests passing and then do a release.

Then we can take a look at the outstanding PRs and see what should be merged...

**Comment by brey** [comment]
I totally support this. We have a `conda-forge` package that relies on `pydap` and we really need to be able to include it in our recipe and not rely on a `pip install` of a specific commit afterwards. Do you have a timeframe? It will inform our next release.

**Comment by captainkirk99** [comment]
Hopefully this will happen in the next few weeks.

**Comment by captainkirk99** [comment]
Note there are a number of additional fixes requested for this release in #122.

Also the suggestion that the next release be called 3.3.0.

**Comment by captainkirk99** [comment]
I have started the draft release notes in the GitHub "Releases" page for this repo. Comments welcome...

**Comment by captainkirk99** [comment]
This has been released.

**Comment by pbregener** [comment]
Hi @captainkirk99,
I am using the 3.3.0 release from `conda-forge`, but just realized that 3.2.2 is still the latest one on `pypi`. Any chance that you can publish the update there as well?
