### ISSUE TITLE
Documentation does not provide information how to display raw data

### ISSUE THREAD

**Issue by kedziorm** [pydap/pydap#25]
When I copy link (sample_query) contained within my gist:
[https://gist.github.com/kedziorm/619141108839f154a8ded009d9cb30e8](https://gist.github.com/kedziorm/619141108839f154a8ded009d9cb30e8)
and paste it to the web-browser, I see raw data.

However, I have no idea how to get exactly the same data in ASCII format using pydap.

![python dataset retrieved from pydap - query for existing data](https://cloud.githubusercontent.com/assets/4739662/20017582/8fc32d4e-a2c4-11e6-82ee-7565061c8549.png)
![python dataset retrieved from pydap](https://cloud.githubusercontent.com/assets/4739662/20017588/9441fc6a-a2c4-11e6-9e20-9010857fec5c.png)

**Comment by jameshiebert** [comment]
I would look [here](http://www.pydap.org/en/latest/client.html#accessing-sequential-data) in the docs for a bit of an explanation. In general, you need to iterate over the data to access individual elements. The proxy types are lazy in that they only download the data values when you iterate over them. In your case this might be something like:

```python
for value in dataset.result.result:
    # do something
# or
my_numpy_array = dataset.result.result[:]
```

**Comment by kedziorm** [comment]
Thank you for help. However, when typing:

`dataset.result.result[:]`

or

```
for value in dataset.result.result:
	print(value)
```

I receive an error:

> ---------------------------------------------------------------------------
> ClientError                               Traceback (most recent call last)
> <ipython-input-17-adfde0af5f1c> in <module>()
> ----> 1 dataset.result.result[:]
> 
> /usr/local/lib/python2.7/dist-packages/pydap/model.pyc in __getitem__(self, index)
>     190 
>     191     def __getitem__(self, index):
> --> 192         return self.data[index]
>     193 
>     194     @property
> 
> /usr/local/lib/python2.7/dist-packages/pydap/proxy.pyc in __getitem__(self, index)
>     113                 fragment))
>     114 
> --> 115         resp, data = request(url)
>     116         dds, xdrdata = data.split('\nData:\n', 1)
>     117         dataset = DDSParser(dds).parse()
> 
> /usr/local/lib/python2.7/dist-packages/pydap/util/urs.py in new_request(url)
>      94                     data, re.DOTALL | re.MULTILINE)
>      95             msg = 'Server error %(code)s: "%(msg)s"' % m.groupdict()
> ---> 96             raise ClientError(msg)
>      97 
>      98         return resp, data
> 
> ClientError: 'Server error 0: "constraint parsing failed; Encountered \'<EOF>\' at line 1, column 44.\nWas expecting one of:\n    \'*\' ...\n    <ID> ...\n    <INT> ...\n    <FLOAT> ...\n    <STR> ...\n
> 
> 
> 
![client error pydap](https://cloud.githubusercontent.com/assets/4739662/20033060/5257e3bc-a398-11e6-9a06-0273ab8f05c9.png)

**Comment by kedziorm** [comment]
@jameshiebert I amended my code: [https://gist.github.com/kedziorm/619141108839f154a8ded009d9cb30e8](https://gist.github.com/kedziorm/619141108839f154a8ded009d9cb30e8)
but I still receive error message.

Is it possible that server returns data which does not fit requirements described in protocol documentation?

```
getSampleData()
<class 'pydap.model.DatasetType'>
{'result': {'result': <pydap.model.BaseType object at 0x7f2f42c8b590>, 'time': <pydap.model.BaseType object at 0x7f2f42c8b750>, 'lev': <pydap.model.BaseType object at 0x7f2f42c8b890>, 'lat': <pydap.model.BaseType object at 0x7f2f42c8b8d0>, 'lon': <pydap.model.BaseType object at 0x7f2f42c8b910>}}
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-6-fca8c5905553> in <module>()
----> 1 getSampleData()

<ipython-input-5-722cbe2b83c2> in getSampleData()
    106     print(type(dataset))
    107     print(dataset)
--> 108     dataset.result.result[:]

/usr/local/lib/python2.7/dist-packages/pydap/model.pyc in __getitem__(self, index)
    190 
    191     def __getitem__(self, index):
--> 192         return self.data[index]
    193 
    194     @property

/usr/local/lib/python2.7/dist-packages/pydap/proxy.pyc in __getitem__(self, index)
    113                 fragment))
    114 
--> 115         resp, data = request(url)
    116         dds, xdrdata = data.split('\nData:\n', 1)
    117         dataset = DDSParser(dds).parse()

<ipython-input-1-b3f901ce3b68> in new_request(url)
     85             msg = 'Server error %(code)s: "%(msg)s"' % m.groupdict()
     86 
---> 87             raise ClientError(msg)
     88         return resp, data
     89 

ClientError: 'Server error 0: "constraint parsing failed; Encountered \'<EOF>\' at line 1, column 44.\nWas expecting one of:\n    \'*\' ...\n    <ID> ...\n    <INT> ...\n    <FLOAT> ...\n    <STR> ...\n    "'

```


![servererrorpydap](https://cloud.githubusercontent.com/assets/4739662/20171023/295da506-a72f-11e6-94ce-c2a466128102.png)

**Comment by jameshiebert** [comment]
Hmm that's... interesting. The error *is* coming back from the server side, but PyDAP does do some construction/modification of the constraint expression before it sends the request to the server. So it's *possible* that it's mangling it incorrectly. I'll flag this as a possible bug, but it would require a little more investigation to confirm.

**Comment by laliberte** [comment]
@kedziorm, since you're only using the ``pydap`` client, you could try using an older ``pydap`` version. I have written a simple patched up package based on ``pydap 3.1.1`` that can handle NASA URS authentication in the very same way that ``pydap 3.2.0`` does. You can find this package at [netcdf_4_pydap](github/laliberte/netcdf4_pydap). It offers a simple interface that is similar to ``netcdf4-python``.

**Comment by kedziorm** [comment]
@laliberte I'm receiving 404 error when trying to open mentioned by you repository.
@jameshiebert I think that my sample query was incorrect (it was http, not https), so I changed it.
However I'm still receiving an error: https://gist.github.com/kedziorm/619141108839f154a8ded009d9cb30e8/revisions

**Comment by laliberte** [comment]
@kedziorm,

I'll have to spend some time to investigate this problem. Notice that I have made a recent PR (#57)  that solves some issues with URS authentication. I guess you could use the associated branch and check whether that solves your problem in the meantime.

**Comment by laliberte** [comment]
@kedziorm 

I've gone through your script and I was to query the dataset you want using PR #57:
```
from pydap.client import open_url
from pydap.cas.urs import setup_session

sample_query = 'https://hydro1.gesdisc.eosdis.nasa.gov/dods/GLDAS_NOAH025SUBP_3H'

session = setup_session(myLogin, myPassword, check_url=sample_query)
dataset = open_url(sample_query, session=session)
test = dataset['rainf'].array[2000, 500:510, 500:510]
```

It turns out the ``check_url`` option is very important for URS authentication. I've updated the docs in #57 to reflect this requirement.

**Comment by jameshiebert** [comment]
We're safe to close this with #57 merged, right? Feel free to reopen if not.
