### ISSUE TITLE
release new version to pypi?

### ISSUE THREAD

**Issue by mathause** [pydap/pydap#268]
pydap 3.3 is [released on conda](https://anaconda.org/conda-forge/pydap) but [not on pypi](https://pypi.org/project/Pydap/) - would be nice if it could also be released to pypi (#267,  pydata/xarray#6960) so it can be installed properly via pip.

**Comment by headtr1ck** [comment]
See also https://github.com/pydap/pydap/issues/212

**Comment by kandersolar** [comment]
With versions 3.4.0 and 3.4.1 on [PyPI](https://pypi.org/project/pydap/#history) now, perhaps this issue can be closed?

**Comment by owenlittlejohns** [comment]
Thanks @kandersolar - yes, we now have [a GitHub workflow](https://github.com/pydap/pydap/blob/master/.github/workflows/publish_to_pypi.yml) that allows us to easily publish to PyPI. It triggers either on the publication of a new GitHub release, or a manual invocation from a maintainer of the repo.
