### ISSUE TITLE
Input timeout value in dap.py not properly propagated down to BaseProxy and SequenceProxy

### ISSUE THREAD

**Issue by jgliss** [pydap/pydap#269]
Refers to module `pydap.handlers.dap.py`.

Class `DAPHandler` has input option `timeout` which is not passed on to inits of `BaseProxy` and `SequenceProxy` in when instantating `DAPHandler`. 

I do not have the full overview here but I believe most of the actual data fetching from remote sources happens via `BaseProxy`. I ran into issues with the 120s default timeout trying to access rather large grids from an OpenDAP thredds server, which occasionally resulting in timeout errors. 

I use `xarray` with `pydap` backend to access such data and I am testing the recently added feature therein to parse a custom timeout for requests, for details see:

https://github.com/pydata/xarray/pull/6276

I will make a PR to propose an update, which I believe will fix these timeout issues.

**Comment by Mikejmnez** [comment]
It looks like this issue should have been closed by #270. Closing now, but feel free to re-open it the issue remains...
