### ISSUE TITLE
namespace_packages deprecated

### ISSUE THREAD

**Issue by mathause** [pydap/pydap#277]
namespace_packages as defined in 
https://github.com/pydap/pydap/blob/35077495efc253116bf0d08f99b56eec82135bad/src/pydap/tests/__init__.py#L1

are deprecated. See also https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages and matplotlib/matplotlib#25244

**Comment by Mikejmnez** [comment]
Thank you @mathause . I will be working on this and similar issues related to older code on pydap as detailed in #295
