### ISSUE TITLE
Pydap handlers not found during installation

### ISSUE THREAD

**Issue by thisistaimur** [pydap/pydap#285]
I am trying to set up a Pydap server using Docker. For this purpose, I put all the Pydap dependencies and handlers in the requirements.txt file (see below). However, when I build the Docker image, it raises errors for the handlers and the handlers for CSV and HDF5 are not available as a result. 

![Screenshot 2023-06-12 at 10 16 01](https://github.com/pydap/pydap/assets/59065240/dcc0b1a4-fa34-47c5-8341-38c022e68ee6)

This method for installing the handlers raises errors as below:

![Screenshot 2023-06-12 at 10 17 57](https://github.com/pydap/pydap/assets/59065240/42c32d5f-77a5-4b0f-b232-5b00602df2f3)

I have tried using the another suggested method for handlers installation as well:

![Screenshot 2023-06-12 at 10 18 48](https://github.com/pydap/pydap/assets/59065240/ed380088-cc79-47b8-a5d8-bc179000a9d3)

However, this method too raises the follow errors during the installation processes

```python
WARNING: pydap 3.3.0 does not provide the extra 'handlers-csv'
WARNING: pydap 3.3.0 does not provide the extra 'handlers-netcdf'
WARNING: pydap 3.3.0 does not provide the extra 'handlers-hdf5'
```

The result of these errors is that the Pydap installation does not work for CSV or HDF5 files. But somehow it works for netCDF4 file (guessing the handler comes in the native installation). Any help on how to get the HDF5 and CSV handlers to work would be much appreciated!

**Comment by thisistaimur** [comment]
Anyone willing to help?

**Comment by Mikejmnez** [comment]
Just to be add to the explanation. The reason why `pydap` works for `netcdf` files even without pre-installing any handler for `netcdf`,  is that `pydap` can access `scipy`'s `netcdf` library if it fails to import any NETCDF library.

**Comment by thisistaimur** [comment]
Thanks, I was able to solve the issue by installing the edited handler from Pacific Climate Impact Consortium: https://github.com/pacificclimate/pydap.handlers.csv
