### ISSUE TITLE
Can't access attributes/coordinates 

### ISSUE THREAD

**Issue by Gilaverbuch** [pydap/pydap#287]
Hi, 

I am trying to get sattelite sst data via
`dataset = open_url('http://tds.maracoos.org/thredds/dodsC/AVHRR/2019/1Agg')`

The dataset type is of the form:
`<DatasetType with children 'lon', 'lat', 'time', 'mcsst'>`

I can download the mcsst data, but I am not sure how to access the lat, long, and time variables. Initially they are None values but when I try downloading the data using `dataset.lon/lat/time.array[:]` I get the following error:

`AttributeError: '<class 'pydap.model.BaseType'>' object has no attribute 'array'`

Any advice here?

Thanks,
Gil

**Comment by Mikejmnez** [comment]
Hi @Gilaverbuch 
Thanks for the issue. Looks like it has been some time. You most likely figured it out by now, but this is what worked for me:

```python
import numpy as np
import matplotlib.pyplot as plt
from pydap.client import open_url


dataset = open_url('http://tds.maracoos.org/thredds/dodsC/AVHRR/2019/1Agg')

lon = dataset['lon'][:].data
lat = dataset['lat'][:].data
time = dataset['time'][:].data
Lon, Lat = np.meshgrid(lon, lat)

mcsst = dataset['mcsst']['mcsst'][0, :, :].data
mtdt = dataset['mcsst'].attributes

DATA = np.squeeze(mcsst[0])

data = DATA.ravel()
mask = data != mtdt['_FillValue']
data[~mask] = np.nan
Data = np.reshape(data, np.shape(DATA))

plt.contourf(Lon, Lat, Data, 100, cmap='jet')
plt.colorbar()
```

It produced the following figure:

![Screenshot 2024-03-15 at 11 15 53 AM](https://github.com/pydap/pydap/assets/8241481/1da655b2-f6e2-4283-8735-637bae16ae70)


python '3.10'
numpy '1.26.4'
pydap 3.4

**Comment by Mikejmnez** [comment]
Will close this as completed. Feel free to re open. Thanks again!
