### ISSUE TITLE
Include verify=self.verify within add_dap4_proxies() and add_dap2_proxies()

### ISSUE THREAD

**Issue by jjrob** [pydap/pydap#288]
In these two functions: https://github.com/pydap/pydap/blob/a330c563c2396c98271fda699c07ab05b7a472b3/src/pydap/handlers/dap.py#L127-L149 the calls to `BaseProxyDap4()`, `BaseProxyDap2()`, and `SequenceProxy()` should include `verify=self.verify`, i.e.:
```python
 def add_dap4_proxies(self): 
     # remove any projection from the base_url, leaving selections 
     for var in walk(self.dataset, pydap.model.BaseType): 
         var.data = BaseProxyDap4(self.base_url, var.name, var.dtype, var.shape, 
                                  application=self.application, session=self.session, 
                                  timeout=self.timeout, verify=self.verify)    # Add verify
     for var in walk(self.dataset, pydap.model.GridType): 
         var.set_output_grid(self.output_grid) 
  
 def add_dap2_proxies(self): 
     # now add data proxies 
     for var in walk(self.dataset, pydap.model.BaseType): 
         var.data = BaseProxyDap2(self.base_url, var.id, var.dtype, var.shape, 
                                  application=self.application, session=self.session, 
                                  timeout=self.timeout, verify=self.verify)    # Add verify
     for var in walk(self.dataset, pydap.model.SequenceType): 
         template = copy.copy(var) 
         var.data = SequenceProxy(self.base_url, 
                                  template, 
                                  application=self.application, 
                                  session=self.session, 
                                  timeout=self.timeout,
                                  verify=self.verify)    # Add verify
```
This is important because the `verify` parameter is ultimately passed to the underlying http library, `requests`, which allows `verify` to be the path to a CA bundle to use (see https://requests.readthedocs.io/en/latest/api/) This allows you to access https-hosted opendap servers that have private certificates, etc. Currently, you can open the datasets with pydap (`open_url()`) but once you actually try to download data, it fails because `verify` is not being passed through these functions.

Thank you for maintaining pydap and for considering this issue.

**Comment by jjrob** [comment]
Hmm, I'll try to come up with something but I'm not sure I can. When this originally came up, I was working on a machine where the operating system's CA bundle was not up to date, and I was trying to talk to a NASA server that had a certificate from a CA that the operating system did not recognize. I wanted to use the `verify` parameter to provide my own CA bundle to work around it. But that failed because the CA bundle file was not being passed all the way down to `requests`.

So we need to create a similar situation somehow. In your test environment, can you:
1. Temporarily tamper with the default CA bundle and remove a CA that will break the chain of trust to a well-known opendap server?
2. Then provide a CA bundle file to `verify` and validate that you can access the server again?

That seems like the easiest way to do it. Alternatively, could you set up an opendap server with a self-signed cert, validate you can't access it, then use `verify` to provide a CA bundle that includes it, and validate that you can access it after all? Unfortunately I don't have an opendap server myself that I can offer for this test.

**Comment by Mikejmnez** [comment]
Sorry for the radio silence, I meant to reply earlier. It turns out that already `verify=True` as default in the definition of the Proxy functions. But like you observed, the value set by the user was not being passed along. What I mean is that for example:

https://github.com/pydap/pydap/blob/02e49a6bf348f2aeb093bea7038a7ab2fb7a3de9/src/pydap/handlers/dap.py#L341-L370

always, even though as you found, `verify` was not being passed along (whether it was `True` or `False`, it was always defined as True in the Proxy fns).

However, in the most recent PR (#373) I did follow your suggestion to allow the parameter`verify` by the user, to be passed along to the Proxy functions as suggested in your comment.
