### ISSUE TITLE
rename `master` branch to `main`

### ISSUE THREAD

**Issue by Mikejmnez** [pydap/pydap#291]
Long over due. For more, read here: https://github.com/github/renaming

Will close issue after renaming branch.

**Comment by Mikejmnez** [comment]
@jgallagher59701 I do not have the permissions to rename the branch. Could you rename the branch to main? [Here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#renaming-a-branch) are the steps to do it (fairly simple).

Once you rename to main, I will make sure to update all workflows to point to `main`. Thanks!

**Comment by jgallagher59701** [comment]
Done
