### ISSUE TITLE
run pre-commit on PRs and have auto updates

### ISSUE THREAD

**Issue by Mikejmnez** [pydap/pydap#311]
### Description
I would like to set up [pre-commit](https://github.com/pre-commit/action) to run on GH as an action. It would run on every PR, and it should periodically trigger PR updating the hooks.

There are two ways to do this,

1) Add a pre-commit.yml file under `.github/workflows`. You can see this repo for more details: [pre-commit/action](https://github.com/pre-commit/action). This action is in maintanance mode, but it is pretty direct.
2) Have  [pre-commit ci](https://pre-commit.ci/) install on Pydap's repo. 

In both scenarios, a `.pre-commit-config.yaml` file is needed in the main directory of pydap with the appropriate configuration (hooks, id, etc etc). You can read more about the hooks pre-commit runs in the documentation [here](https://pre-commit.com/). 

### What I did

I have already included the `.pre-commit-config.yaml` with the appropriate configuration on Pydap.

However, I tried option 2) above, to add pydap onto as an installation on pre-commit ci. It looks like the request needs to be approved and after a couple of days (or more) it states that it is pending. You can see from the screenshot below:

<img width="350" alt="Screenshot 2024-04-23 at 9 15 20 PM" src="https://github.com/pydap/pydap/assets/8241481/287664d1-7718-4296-aa20-117057dd59a7">

I never got an email about this. Did you @jgallagher59701 ? 

It may be that the easier way to move forwards with this is to manually create a github action worflow, as detailed in option 1). It requires minimal changes and should work right away.

**Comment by jgallagher59701** [comment]
I think I did get an email, but that's because I set up notifications in my GitHub profile just recently. It was pretty complicated - I could not replicate the process other than to say that I googled to learn how to set those options.

Are you wanting to get something automated to reformat your source code when you push a commit to GitHub? (If so, that is what I want as well and I don't know exactly how to do it, but I know we used to do it using Subversion so I think
 it's possible)

**Comment by Mikejmnez** [comment]
There are two ways to set up some formatting on github with pre-commit. One of the ways is to do it manually, which I ended up doing in PR #312. And So We can cancel the online request since it is no longer needed.


What pre-commit does:
1) Applies automatic rules for linting, spacing, length of lines, whitespace, etc. Each of these is a specific hook.
2) Requires a configuration file. This is the `pre-commit-config.yaml` already at the root of this repo. You can check all the specifications I defined is such file.
3) It can run locally on the developers computer. It requires installation once, and everytime there is a commit, `pre-commit` runs on all files. When necessary makes automatic corrections, but it may not always be able to fix things automatically (for example whitespaces between operators).
4) Can trigger automatic PRs to be continuously be updated with respect to the newer formatting requires by latest Python version format. In that scenario, the PR will only change the file `/.github/workflows/pre-commit.yml`, but these updates can trigger a fail during the testing. But this way the code can be kept up to date for formatting standards.


1-3) Already are True for Pydap. PR #312 allows for 4).

**Comment by Mikejmnez** [comment]
Closed by #312
