### ISSUE TITLE
`pydap` appears to be incompatible with `numpy>=2`

### ISSUE THREAD

**Issue by keewis** [pydap/pydap#321]
### Description

Importing `pydap.client` fails if `numpy>=2` is installed (noticed in `xarray`'s CI).

### Minimal example that reproduces the bug, or a new desired feature

With `numpy>=2` in the environment:

```pytb
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import pydap.client

File .../lib/python3.11/site-packages/pydap/client.py:53
     51 import pydap.lib
     52 import pydap.net
---> 53 import pydap.handlers.dap
     54 import pydap.parsers.dds
     55 import pydap.parsers.dmr

File .../lib/python3.11/site-packages/pydap/handlers/dap.py:16
     14 import re
     15 from itertools import chain
---> 16 from numpy.lib.arrayterator import Arrayterator
     18 # handlers should be set by the application
     19 # http://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library
     20 import logging

ModuleNotFoundError: No module named 'numpy.lib.arrayterator'
```

<details><summary>Environment</summary>

```
python : 3.11.9 (conda-forge)
numpy: 2.0.0
pydap: 3.4.0
```

</details>

**Comment by Mikejmnez** [comment]
Thanks @keewis I'll take a look into this. There are a couple of things that need to be worked to bring pydap into full re-compatibility with xarray, I will add this to the list

**Comment by nick-dawson** [comment]
I manually updated the Arrayterator imports from "numpy.libarrayterator import Arrayterator" to "from numpy.lib import Arrayterator" which fixed that problem, but other issues happened after that.
