### ISSUE TITLE
AttributeError: '<class 'pydap.model.BaseType'>' object has no attribute '_is_string_dtype'

### ISSUE THREAD

**Issue by Mikejmnez** [pydap/pydap#347]
### Description

This error is confusing, because the object is indeed a `pydap.model.BaseType` and `_is_string_dtype` is a property of `BaseType`. This error only happens when trying to download data of a global dimension variable into memory, but the dataset creation goes smoothly.

### Minimal example
For this example, I am trying to access NASA data, and so it requires `token` authentication, read from a JSON file . The JSON file is created following the [GetStarted](https://github.com/OPENDAP/ESIP2024/blob/main/binder/GetStarted.ipynb) tutorial.

```python
from pydap.client import open_url
import requests
import json
import requests

# load token json data
with open('token.json', 'r') as fp:
    Authorization = json.load(fp)

# pass Token Authorization to a new Session.
my_session = requests.Session()
my_session.headers = Authorization


# dataset parameters
filename = 'Daymet_Daily_V4R1.daymet_v4_daily_na_tmax_2010.nc'
hyrax_url = 'https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/'
url = hyrax_url + filename

## THIS DOES NOT WORK
ds = open_url(url, session=my_session, protocol='dap4')
ds.tree()
.daymet_v4_daily_na_tmax_2010.nc
├──y
├──lon
├──lat
├──time
├──x
├──tmax
├──lambert_conformal_conic
├──time_bnds
├──yearday
└──nv
```

The above works nicely. It is only when attempting to download data for the variable `nv` that I get the error:
```python
for child in ds.keys():
    print(child, ds[child].shape)
    if ds[child].ndim==1:
        ds[child][0]
    elif ds[child].ndim==2:
        ds[child][0,0]
    elif ds[child].ndim==3:
        ds[child][0,0,0]
```
yields:
```python
y (8075,)
lon (8075, 7814)
lat (8075, 7814)
time (365,)
x (7814,)
tmax (365, 8075, 7814)
lambert_conformal_conic ()
time_bnds (365, 2)
yearday (365,)
nv (2,)
AttributeError: '<class 'pydap.model.BaseType'>' object has no attribute '_is_string_dtype'
```

This means the variable `nv` is the one causing the trouble. For example:

```python
import pydap
print(isinstance(ds['nv'], pydap.model.BaseType)
>>> True
print(isinstance(ds['lon'], pydap.model.BaseType))
>>> True
print(ds['lon']._is_string_dtype)
>>> False
```
but
```python
try:
    ds['nv']._is_string_dtype
except:
    print('error')
>>> error
```

Interestingly enough, the variable `nv` is the only one that is listed as `Global Dimension`, but does not appear explicitly as a `Variable` in the Data Request Form (see [here](https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/Daymet_Daily_V4R1.daymet_v4_daily_na_tmax_2010.nc.dmr.html)). And so you cannot download even from the browser...

`nv` (and `niter`) is dimensions that are always `length=2` and can be defined as `np.array([0,1])`.

### solution

I think that since this variable cannot be downloaded, and it ALWAYS `ndim=1` and has `length=2`, it can be created locally. This would only be done when:
- it appears as a global dimension
- It does not appear as a Variable in the dataset
- ndim = 1
- len = 2

**Comment by Mikejmnez** [comment]
FYI:
The following (when encoded) URL **works** and triggers a download from the DAP4 Data Request form:

https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/Daymet_Daily_V4R1.daymet_v4_daily_na_tmax_2010.nc.dap.nc4?dap4.ce=/time[0:1:364];/time_bnds[0:1:364][0:1:1]


But if I include the Global Dimension `/nv` (i.e. append a `;/nv` to the URL above) I get a Hyrax - Bad Request (400). In particular:

```python
It appears that you have submitted a Bad Request.

The specific error message associated with your request was:

FONcTransmitter::send_dap4_data() - Failed to read data: The constraint expression referenced a variable that was not found in the dataset
```

And so indeed pydap (and too`xarray`) has trouble accessing data for the remote Global dimension `/nv`, which is simply `nv=[0,1]`. I believe this will always happen to a `Global Dimension` that is named in the DMR of a dataset, but that is not part of the dataset.

## solution
Pydap needs to create this variable  - there is no Proxy Data (remote data) associated with the variable, but the DMR describe all what is needed for `nv` to be well defined. Namely:

nv = BaseType('nv', np.arange(2), dtype=np.int64)

**Comment by ndp-opendap** [comment]
So in this case, /nv is NOT a variable it is a named Dimension that exists at the top level (root group) of the dataset. It is correctly represented in the DMR:
```
<Dimension name="nv" size="2"/>
```
And can be seen in the [DataRequestForm](https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/Daymet_Daily_V4R1.daymet_v4_daily_na_tmax_2010.nc.dmr.html) by examining the Global Dimensions list.

Because of this I question if making a variable to represent it is the correct move, as it has no data and cannot ever have data (since it is only a Dimension)
Is there an issue with the way that pyDAP is handling Dimensions that do not have an associated/dedicated array variable ?

**Comment by Mikejmnez** [comment]
Yes, it is a `Dimension`, but as you can see in the [DataRequestForm](https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/Daymet_Daily_V4R1.daymet_v4_daily_na_tmax_2010.nc.dmr.html), it DOES define data =  `[0, 1]`. This is also evidently true when working with `xarray`:

<img width="400" alt="Screenshot 2024-08-13 at 9 44 17 PM" src="https://github.com/user-attachments/assets/bbe5d8b2-25c5-40dd-91ec-ec2fcac1664a">



(to provide some more context -  I am trying to have PyDAP be consistent with xarray to assure easy integration).

@ndp-opendap to answer your question:

> Is there an issue with the way that pyDAP is handling Dimensions that do not have an associated/dedicated array variable ?

Yes! Currently, when a `Global Dimension`does NOT have an associated array/variable with the same name, it automatically gets assigned one. This causes pydap to assign a `Dummy Data` type to `nv`, essentially an empty array with `shape` and `dtype` attributes. Here one part of the relevant code:

https://github.com/pydap/pydap/blob/c98fa3e2149eb34ffe99084521a1ff51c3749c14/src/pydap/parsers/dmr.py#L182-L195


And so with this insights, it leads me to the alternate solution:

### alternate solution
Following @ndp-opendap comments/suggestions, I removed the snippet above where `PyDAP` makes all dimensions have an array/variables with the same name. `nv` still shows up as a dimension for `time_bnds`, but `nv no longer appears as a variable in the dataset`. To make things work I also had to make some changes in the dmr parser, but now things work :) 

For example:

```python
ds = open_url(url, session=my_session, protocol='dap4')
ds.tree()
.daymet_v4_daily_na_tmax_2010.nc
├──y
├──lon
├──lat
├──time
├──x
├──tmax
├──lambert_conformal_conic
├──time_bnds
└──yearday
```
With `xarray`, things now work as expected and `nv` correctly appears as a `Dimension`, non-bold, which means it is not a coordinate (dimension that is also a variable).

 
<img width="779" alt="Screenshot 2024-08-13 at 10 02 59 PM" src="https://github.com/user-attachments/assets/0742e176-e6d4-4a07-b774-5e9321995a40">


Thanks @ndp-opendap !
