### ISSUE TITLE
Switch pydap.handlers.netcdf to use scipy instead of pupynere

### ISSUE THREAD

**Issue by shoyer** [pydap/pydap#36]
Scipy's netcdf3 file handling is a maintained fork of pupynere, so (for example) it also runs on Python 3.

Any concerns?

**Comment by laliberte** [comment]
That's what I did in #35. I assumed this was the only way to go since ``pupynere`` does not seem to be actively maintained and is not even on github.

**Comment by shoyer** [comment]
Oh, very nice, I missed that.

**Comment by jameshiebert** [comment]
Yeah, that's a good idea. Should this be filed against https://github.com/pydap.pydap.handlers.netcdf ?

**Comment by laliberte** [comment]
Yes, most likely. But in fact, in PR #35 I kind of suggest that maybe we should merge [handlers.netcdf](https://github.com/pydap.pydap.handlers.netcdf) into ``pydap``.
