### ISSUE TITLE
There are four ways to specify Attributes on DAP4 spec - Pydap should be able to parse all

### ISSUE THREAD

**Issue by Mikejmnez** [pydap/pydap#406]
### Description

The DAP4 specification allows for three ways to define an attribute (see [section 1.5.14](https://opendap.github.io/dap4-specification/DAP4.html#_attributes_and_arbitrary_xml) ):

1. Option 1 (tds does this)
```python
<Attribute name="name" type="{atomicTypeName|EnumType fqn}" value="value"/>
```

2. Option 2 (hyrax)
```python
<Attribute name="name" type="{atomicTypeName|EnumType fqn}"/>
  <Value>Value</Value>
</Attribute>
```

3. Option 3 (tds also does this)
```python
<Attribute name="name" type="{atomicTypeName|EnumType fqn}"/>
  <Value value="value"/>
</Attribute>
```

4. Option 4 
```python
<Attribute name="name" type="{atomicTypeName|EnumType fqn}">
  <Namespace href="http://netcdf.ucar.edu/cf"/> <!--optional-->
  <Value value="value"/>
  ...
  <Value value="value"/>
</Attribute>
```
Note that in this Option 4, multiple value are being defined for this single attribute, and that is valid scenario. What happens here then is that result should be a **vector of values** for that attributes.

Pydap can already, can parse attributes when there are defined following Options 1-3. But not Option 4

**Comment by ndp-opendap** [comment]
Hyrax also produces option 2 with multiple values. 

I think we need to consider/plan-for/anticipate possible heterogeneous examples:
```xml
<Attribute name="name" type="{atomicTypeName|EnumType fqn}" value="value">
<Value value="another value"/>
<Value>yet anther value</Value>
```
