### ISSUE TITLE
pydap takes a very long time to translate .dap document to array data with dap4

### ISSUE THREAD

**Issue by Mikejmnez** [pydap/pydap#418]
### Description

I am looking at [this file](https://oceandata.sci.gsfc.nasa.gov/opendap/PACE_OCI/L3SMI/2024/1203/PACE_OCI.20241203.L3m.DAY.CHL.V2_0.chlor_a.4km.NRT.nc.dmr) from PACE. In fact, any will do. I can manually download data just fine through the DAP Web Service, including the .dap file in seconds.

### Minimal example that reproduces the bug, or a new desired feature

```
from pydap.client open_url
url = 'http://oceandata.sci.gsfc.nasa.gov/opendap/PACE_OCI/L3SMI/2024/1203/PACE_OCI.20241203.L3m.DAY.CHL.V2_0.chlor_a.4km.NRT.nc'
```
### protocol='dap2' works fine
this completes a download in 3-4 seconds:
```python
pyds = open_url(url,protocol='dap2')
pyds['chlor_a/chlor_a'][:]
```

#### protocol='dap4' takes a very long time to download
This takes 3-4 minutes!!!
```python
pyds = open_url(url,protocol='dap4')
pyds['/chlor_a'][:]
```

The first line is pretty fast, which means that the DMR parser works fine. 
The problem is then when streaming binary data from the dap file to numpy arrays. That is something that I am not super familiar.

NOTE that this issue has been ongoing since at least [August 1](https://github.com/pydap/pydap/pull/337) when I first created the new documentation and included an example using PACE data. You can see [here](https://pydap.github.io/pydap/notebooks/PACE.html#lets-download-some-data) that downloading data takes 3 minutes! but a subset of it is pretty fast.

**Comment by ndp-opendap** [comment]
This is odd... 
Is the dap2 data also loaded into a numpy array?

**Comment by Mikejmnez** [comment]
yes it is... I ran the test on a notebook.Dunno if it is relevant but here are the outputs from downloading data:


### protocol='dap2'
```python
<BaseType with data array([[-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       ...,
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.]],
      dtype='>f4')>
```
and with protocol='dap4'

```python
<BaseType with data array([[-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       ...,
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.]],
      dtype=float32)>
```

**Comment by Mikejmnez** [comment]
it is clearly a pydap problem - just a matter of figuring out where exactly. I am not very familiar with this part of the code within pydap. 

Might take me a couple of hours to figure out what is going on and come up with a fix

**Comment by ndp-opendap** [comment]
This:

> dtype='>f4'

Is interesting

**Comment by ndp-opendap** [comment]
Also, dap4 has this idea of _reader makes right_ when it comes to endianness. I wonder: Is there is some issue/inefficiency in that part of the reader that handles the endianness conversion? Or even in the non-conversion situation...

**Comment by Mikejmnez** [comment]
> This:

  >>  dtype='>f4'

> Is interesting

Yes! I was just doing this:

```python
ds4 = open_url(url, protocol='dap4') 
ds2 = open_url(url, protocol='dap2') 

data2 = ds2['chlor_a/chlor_a'][:]
data4 = ds4['/chlor_a'][:]

```

and then did this:

```
print(data2.dtype)
>>> dtype('>f4')
```

```
print(data4.dtype)
>>> dtype('<f4')
```

**Comment by ndp-opendap** [comment]
ok - a python artifact then

**Comment by Mikejmnez** [comment]
I spend some time looking at this. I think the issue is the lack of parallellization when getting the bytes and turning them into an array. 

the following code downloads  into memory the .dap associated only with chlor_a (0.15 Gbytes), and takes 2 seconds:

```python
url = "http://oceandata.sci.gsfc.nasa.gov/opendap/PACE_OCI/L3SMI/2024/1203/PACE_OCI.20241203.L3m.DAY.CHL.V2_0.chlor_a.4km.NRT.nc.dap"
r = GET(url+"?dap4.ce=/chlor_a")

dmr, data = safe_dmr_and_data(r, 'ascii', url)
# empty dataset with chlor_a variable
dataset = dmr_to_dataset(dmr)

xdr_stream = BytesReader(data)  # just reads the binary
```

The following gets the binary `data` and sequentially, chunk by chunk, get the size of the array buffer. It takes almost 3 minutes!
```python
dataset = unpack_dap4_data(BytesReader(data), dataset)
```
where
https://github.com/pydap/pydap/blob/5ed032602cd9edc29a24a11031c21b654443baac/src/pydap/handlers/dap.py#L813-L822


length of data = `149356572`, chunk_size=10411 ,  The `While loop` iterates ~ 14341 times.

**Comment by Mikejmnez** [comment]
This is not inherent to the dataset I showed. Setting protocol='dap4' is always almost many times slower when downloading data with pydap, than setting protocol='dap2'.

**Comment by Mikejmnez** [comment]
Got some new code coming up!

preliminary results:
### old
```python
%%time
buffer = stream2bytearray(binary_dap_data)
>>> CPU times: user 1min 5s, sys: 1min 48s, total: 2min 53s
Wall time: 2min 54s
```
### new
```python
%%time
buffer = newstream2bytearray(binary_dap_data)
>>> CPU times: user 222 ms, sys: 69.4 ms, total: 291 ms
Wall time: 276 ms
```

almost 3 order of magnitude improvement. Data looks correct!!!

**Comment by Mikejmnez** [comment]
Now 
```python
pyds = open_url(url,protocol='dap4')
pyds['/chlor_a'][:]
```
takes 3-4 seconds, compared to 3.5 minutes before! Now most of the time (75%-90%) of time is spend downloading the dap response. Could still need some improvements, but I will take it for now!

**Comment by ndp-opendap** [comment]
is there a branch that could be linked to this ticket?
<img width="327" alt="Screenshot 2024-12-06 at 10 56 52 AM" src="https://github.com/user-attachments/assets/ea0dedee-4190-4edb-8fbe-9ffa5da8a253">

**Comment by ndp-opendap** [comment]
And - nice work!! That's a huge performance gain. And from a usage perspective that went from unusable to usable

**Comment by Mikejmnez** [comment]
yes - do the following on a pydap_test environment:

```python
conda create -n pydap_tests -c conda-forge python=3.10
conda env update -n pydap_tests -f ci/environment.yml
conda activate pydap_tests

pip install --upgrade git+https://github.com/Mikejmnez/pydap@iss428

```

i think that should install the dev branch that I have (got some failing tests), but on lunch break right now

**Comment by ndp-opendap** [comment]
I meant here, on this ticket in GtHub there is a place to link your branch with the patch to this particular ticket,

**Comment by Mikejmnez** [comment]
done - PR is ready for review (I had to take a look at the failing tests)
