### ISSUE TITLE
model.GridType differences from 3.1.1

### ISSUE THREAD

**Issue by MBARIMike** [pydap/pydap#43]
GridType in Version 3.1.1 has __len__() method and other attributes:

    # These attributes all come from the array object.
    def __len__(self): return len(self.array)
    @property
    def type(self): return self.array.type
    def _get_shape(self): return self.array.shape
    def _set_shape(self, shape): self.array.shape = shape
    shape = property(_get_shape, _set_shape)

Should they be added to maintain compatibility?

**Comment by MBARIMike** [comment]
Upon further inspection I see that the GridType returned is different. In Version 3.1.1 I get a dictionary:

```python
>>> from pydap.client import open_url
>>> ds = open_url('http://dods.mbari.org/opendap/data/auvctd/surveys/2010/netcdf/Dorado389_2010_300_00_300_00_decim.nc')
>>> ds['temperature']
{'temperature': <pydap.model.BaseType object at 0x7f18464a7650>, 'time': <pydap.model.BaseType object at 0x7f18464a7750>}
```

With Version 3.2.0 I get something different:

```python
>>> from pydap.client import open_url
>>> ds = open_url('http://dods.mbari.org/opendap/data/auvctd/surveys/2010/netcdf/Dorado389_2010_300_00_300_00_decim.nc')
>>> ds['temperature']
<GridType with array 'temperature' and maps 'time'>
```

Perhaps this is an improvement and I should change my code?

**Comment by taeold** [comment]
This explains some of the compatibility issue I saw in pydata/xarray#1174 - namely, datatype returned by `pydap.client` in version 3.2 is dictionary-_like_ but not quite so, missing couple of functions like `__len__` and `iteritems/items`.

Does it make sense to implement these functions? From my understanding of the code, `GridType`/`StructureType` appeared well equipped to implement those functions (am I naive in thinking so?).

**Comment by MBARIMike** [comment]
It wasn't too hard for me to [make a work-around](https://github.com/stoqs/stoqs/pull/452/commits/44f487e5a5ba35e948dc46c615992e087620a533) in my code, but it'd be nice to have the same behavior that we have 3.1.1.

**Comment by jenfly** [comment]
I'd love to have this compatibility as well!  I'm new to Pydap - I've been using Xarray and now I'm trying to get it to work with `engine=pydap` in order to handle NASA's new authentication procedures.  But the `engine=pydap` option doesn't work in `xarray.open_dataset()` anymore because of these changes to `GridType`.  I can try to make my own versions with workarounds, but going forward it would be great to restore compatibility between Xarray and Pydap again.  Is there any particular reason these attributes were removed?

**Comment by laliberte** [comment]
I'm going to close this one following PR #48. If it turns out to be insufficient, I'll reopen.
