### ISSUE TITLE
Check byte use

### ISSUE THREAD

**Issue by robertodealmeida** [pydap/pydap#5]
I noticed in some places of the code byte is signed, while in others it's unsigned. I should verify how the DAP spec defines it (unsigned, I think) and ensure the proper type in the code.

**Comment by laliberte** [comment]
It is unsigned ([ref.](https://cdn.earthdata.nasa.gov/conduit/upload/512/ESE-RFC-004v1.1.pdf) page 8 Table 2). This should be ensured throughout the code.
