### ISSUE TITLE
Missing extra requires on PasteDeploy

### ISSUE THREAD

**Issue by ghisvail** [pydap/pydap#53]
Even with the all list of dependencies installed, the `pydap` command cannot be run without doing a `pip install PasteDeploy`. Perhaps it would be worth adding it to the list of extra requires for the cli.

**Comment by mihow** [comment]
It looks like the `paste` method used in the simple pydap server script is depreciated and we only need gunicorn to run the pydap server, but the pydap script needs to be updated. 

I can do that during the PyCon sprint!

Here is the warning from gunicorn:
```
!!! WARNING: This command is deprecated.
!!! 
!!!     You should now use the `--paste` option. Ex.:
!!! 
!!!         gunicorn --paste development.ini
```

**Comment by jameshiebert** [comment]
OK cool, so basically if we fix #52, we'll fix this issue as well.

**Comment by jameshiebert** [comment]
Looks like all we have to do is use gunicorn's ``PasterServerApplication`` directly like they have [here](https://github.com/benoitc/gunicorn/blob/master/gunicorn/app/pasterapp.py#L210). Should be a 3 line fix.

**Comment by mihow** [comment]
I believe you can even just use gunicorn's `WSGIApplication` directly and
loose the PasteDeploy dependency, but I haven't tried yet. Similar syntax:
 `WSGIApplication(app, options).run()`

**Comment by jameshiebert** [comment]
Yeah, that'd be better :)

**Comment by Jerry-Ma** [comment]
```
Traceback (most recent call last):
  File "/home/toltec/.local/bin/pydap", line 11, in <module>
    sys.exit(main())
  File "/home/toltec/.local/lib/python3.6/site-packages/pydap/wsgi/app.py", line 225, in main
    from gunicorn.app.pasterapp import PasterServerApplication
ImportError: cannot import name 'PasterServerApplication'
```

The latest gunicorn have moved the class inside the serve function. The code now is broken.
