### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by bucricket** [pydap/pydap#65]
HI do you think you could have a new release?  Then perhaps the latest fixes could be built on conda-forge?

**Comment by ghisvail** [comment]
I second this request.

**Comment by ghisvail** [comment]
Please consider merging #67 and #68 before finalizing the release, as they would significantly improve the package-ability of `Pydap` on Debian. Thanks.

**Comment by ghisvail** [comment]
@jameshiebert Now that #68 is merged and #67 is ready to be, would you consider making a point or micro-release so I can finalize the Debian packaging? Thanks.

**Comment by jameshiebert** [comment]
Hi all! Yes, I *think* that I have all of the "easy" PRs merged such that I would feel good about doing a point release (3.2.1). I'll start working on that...

**Comment by ghisvail** [comment]
Awesome, thanks!

**Comment by bucricket** [comment]
Excellent!

Mitch

**Comment by jameshiebert** [comment]
The new point release (3.2.1) [is up](https://pypi.python.org/pypi/Pydap/3.2.1). Thanks [to everyone](https://github.com/pydap/pydap/blob/master/CONTRIBUTORS.md) who contributed to make it happen!
