### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by robertodealmeida** [pydap/pydap#7]
Python 3 support using the six module is in progress. Finish the port for release 3.2.1.

**Comment by PaulSorenson** [comment]
I noticed the sphinx docs fail in python3.4 on source I cloned from the repo today.  It was only after fixing them I came here.  Since I didn't use six my changes probably aren't appropriate to merge.  I could possibly have a look at doing this with six if nobody else is - any advice you guys have?

**Comment by shoyer** [comment]
@paulsorenson in my experience, six really isn't necessary for mixed Python 2/3 support these days. So I would say it's fine not to use it.

**Comment by lewismc** [comment]
This issue is addressed right? @jameshiebert

**Comment by jameshiebert** [comment]
Indeed it is.
