### ISSUE TITLE
FutureWarning regarding use of structured arrays

### ISSUE THREAD

**Issue by ghisvail** [pydap/pydap#72]
While testing `pydap-3.2.0` on Debian Stretch (Numpy 1.12.x), some tests throw a `FutureWarning` which you guys might want to check out. Here is the relevant part of the nose test log:
```
[...]
Test item retrieval. ... /usr/lib/python3/dist-packages/numpy/core/records.py:507: FutureWarning: Numpy has detected that you may be viewing or writing to an array returned by selecting multiple fields in a structured array.
[...]
Test using density as a selection. ... /usr/lib/python3/dist-packages/numpy/core/records.py:507: FutureWarning: Numpy has detected that you may be viewing or writing to an array returned by selecting multiple fields in a structured array. 
```

**Comment by laliberte** [comment]
PR #55 made sure that views are explicitly converted to copies. There was however no clean ways I could find to suppress these warning messages.

**Comment by laliberte** [comment]
It turns out that in the [newest builds](https://travis-ci.org/pydap/pydap/builds/216181315) this warning is suppressed. @jameshiebert maybe this issue could be closed?

**Comment by laliberte** [comment]
For the reason mentioned above I will close this issue.
