### ISSUE TITLE
Switch tests to pytest?

### ISSUE THREAD

**Issue by laliberte** [pydap/pydap#82]
Should we tweak the tests to make them compatible with ``pytest`` and use ``py.test`` instead of ``nosetests`` on Travis?

**Comment by jameshiebert** [comment]
I really like ``pytest`` (in particular, parametrized test functions). I'd definitely support that. How much do you think it would take to make that happen?

**Comment by laliberte** [comment]
If we go for minimal tweaks, it should be ready in an hour. Then maybe we could slowly modernize the tests to eventually scrub nose out...
