### ISSUE TITLE
Drop support for 3.3

### ISSUE THREAD

**Issue by laliberte** [pydap/pydap#96]
I recommend we drop support for python 3.3. Most major projects are doing the same and security patches will stop being issued by September 2017.

**Comment by matthew-campbell** [comment]
Would you please reference your claim?

**Comment by laliberte** [comment]
This was referenced in [PEP 0398]https://www.python.org/dev/peps/pep-0398/#lifespan). For another project who seemed to have dropped their python 3.3 support, you have [``xarray``](https://pypi.python.org/pypi/xarray/). In that context, do you know of any reason why python 3.3 support should be kept within ``pydap``?

**Comment by shoyer** [comment]
NumPy also no longer supports Python 3.3: https://pypi.python.org/pypi/numpy/

**Comment by laliberte** [comment]
Ok, I did not even notice. That was obvious canary in the coal mine. @shoyer I assume that makes you +1 ? @jameshiebert any objections?

**Comment by shoyer** [comment]
Yes, +1 from me

**Comment by jameshiebert** [comment]
+1
